### ISSUE TITLE
Creating conda Environment is a mess

### ISSUE THREAD

**Issue by amalamal1996** [NasimAbdollahi/NodeCoder#7]
Hello,
can you kindly provide the environment.yml file for cloning the environment.
I am trying to install packages one by one, and it is really very frustrating and also doesn't work.
dependency between the package is not consistent.

it would be great if you can provide the environment.yml file by exporting your condo environment.
thank you very much for the help

**Comment by NasimAbdollahi** [comment]
Hello, 
Sorry to hear this! dealing with inconsistent dependencies is frustrating.
I have added the environment.yml file for cloning the environment, find it in "NodeCoder/src".

**Comment by NasimAbdollahi** [comment]
Hello,
Sorry to hear this! dealing with inconsistent dependencies is frustrating.
I have added the _**environment.yml**_ file for cloning the environment, find it in "NodeCoder/src".
