### ISSUE TITLE
Do I have to train the model?

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [NasimAbdollahi/NodeCoder#8]
Hi, do I have to train NodeCoder in order to predict, or is it already trained? It is not clear to me, e.g, do I have to download AFDB, BioLiP, etc before. predicting on a structure?

**Comment by NasimAbdollahi** [comment]
Hi Javier, 

The NodeCoder Repo, does not include the trained weights. So, you would need to train NodeCoder for the task you are interested in. If the task is in the curated raw data, you can use this data to train NodeCoder. 

NodeCoder comprises source code responsible for generating training and validation graph datasets from raw data. The raw data we used for evaluating NodeCoder consists of three datasets: AlphaFold (860.2 MB), BioLip (32.4 MB) and UniProt (102.3 MB), which can be accessed at https://osf.io/qt5kn/.

**Comment by JavierSanchez-Utges** [comment]
Hi, Nasim, thanks for your answer.

I want to predict ligand bindings, yes. Would it be possible for you to share the weights, to avoid training the models for the users of NodeCoder?

**Comment by NasimAbdollahi** [comment]
Anytime! 
I'd love to find some time to work on this and share the trained weights with the community. I don't have direct access to them anymore. Maybe I'll get around to it in the near future, but I can't make any promises. I'll be sure to keep you posted if anything changes.

**Comment by NasimAbdollahi** [comment]
Anytime! 
I'd love to find some time to work on this and share the trained weights with the community. I don't have direct access to them anymore. Maybe I'll get around to it in the near future, but I can't make any promises. I'll be sure to keep you posted if anything changes.
